import { PhoneIcon, SearchIcon } from "@chakra-ui/icons"
import {
    Box,
    Container,
    Divider,
    Flex,
    Input,
    InputGroup,
    InputLeftElement,
    SimpleGrid,
    useDisclosure,
} from "@chakra-ui/react"
import type { NextPage } from "next"
import Head from "next/head"
import Navbar from "../components/Nav"

const Home: NextPage = () => {
    const { isOpen, onClose, onOpen } = useDisclosure()
    return (
        <Box mt={2}>
            <Head>
                <title>Citadel of the Believer</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <Divider />
            <Container maxW={["sm", "2xl"]} my={4}>
                <InputGroup>
                    <InputLeftElement
                        pointerEvents="none"
                        children={<SearchIcon color="gray.400" />}
                    />
                    <Input type="search" placeholder="search dua" />
                </InputGroup>
            </Container>
            <SimpleGrid columns={[2,3]} spacing={10} mx={[4,4,12]} mt={6} >
                <Flex bg="red.400" height="100px" borderRadius={10}></Flex>
                <Flex bg="blue.400" height="100px" borderRadius={10}></Flex>
                <Flex bg="yellow.400" height="100px" borderRadius={10}></Flex>
                <Flex bg="teal.400" height="100px" borderRadius={10}></Flex>
                <Flex bg="tomato" height="100px" borderRadius={10}></Flex>
                <Flex bg="purple.400" height="100px" borderRadius={10}></Flex>
            </SimpleGrid>
        </Box>
    )
}

export default Home
